### PR TITLE
Feature horror setting

### PR DESCRIPTION
**Pull request by herrozerro**
For #1.  I think I have everything, there are two questions.  Comments inside the setting file. 

1. Talisman craftsman requires magic or miracles, so I just made a version for each.

2. Patchwork Man cannot raise his smarts at all through advances.  I wasn't sure how that is handled.

### CODE REVIEW

**Comment by Grauenwolf** [comment]
The descriptions are rather long, which is a problem for both display purposes and copyrights. So we may have to go back and trim them a bit to be more of a summary than a copy-and-paste from the book.

**Comment by Grauenwolf** [comment]
> Talisman craftsman requires magic or miracles, so I just made a version for each.

There are two options here.

Option 1: Just list it twice using two different names.

```
    <Edge Name="Talisman Craftsman (Magic)" Requires="Novice, Smarts d8, Spirit d8, Arcane Background (Magic), Occult d8, Spellcasting d8" Description="..." />
    <Edge Name="Talisman Craftsman (Miracles)" Requires="Novice, Smarts d8, Spirit d8, Arcane Background (Miracles), Occult d8, Faith d8" Description="..." />
```

Option 2: Use a bunch of `or`s.

```
    <Edge Name="Talisman Craftsman" Requires="Novice, Smarts d8, Spirit d8, Arcane Background (Magic) or Arcane Background (Miracles), Occult d8, Spellcasting d8 or Faith d8" Description="..." />
```

If it would need multiple groups of `or`s, I would just list it twice to make it easier to read.

**Comment by Grauenwolf** [comment]
> Patchwork Man cannot raise his smarts at all through advances. I wasn't sure how that is handled.

That one is tricky. You can set a max smarts easily enough, but there's no way to say "cannot advance smarts". I'll have to think about it.

**Comment by Grauenwolf** [comment]
Added #28 to deal with patchwork man.

**Comment by herrozerro** [comment]
> 
> 
> The descriptions are rather long, which is a problem for both display purposes and copyrights. So we may have to go back and trim them a bit to be more of a summary than a copy-and-paste from the book.

I can do that.  What level of detail is acceptable?  Some of the new powers are quite wordy.  What I can do is summarize them and then leave a page reference like (see pg x of the horror companion)

**Comment by Grauenwolf** [comment]
> What level of detail is acceptable? 

If you look "Edge Summaries" in the main book, that's the level of detail I've been trying to use.

And yes, definitely use a page reference if the text is too long to properly summarize. 

Which raises a question, should we go back and put in page numbers for everything? We could change the XML format to include a place specifically for it.

**Comment by Grauenwolf** [comment]
Changes are live.

**Comment by herrozerro** [comment]
I think a page number in the objects/xml would be a good idea.  then it could be easily excluded in the compact formattings.

**Comment by Grauenwolf** [comment]
Ok, I've got it in the todo list. #29.

**Comment by Grauenwolf** [comment]
By the way, I marked you as a contributor for the project. Anything you merge into the `master` branch will be automatically deployed. So unless you are doing an emergency fix, please continue to use pull requests.

**Comment by herrozerro** [comment]
thanks!

**Pull request merged**
